### ISSUE TITLE
set('foreignSymbols', arr) doesn't work properly

### ISSUE THREAD

**Issue by pcanella** [oscarotero/node-sketch#14]
Hi, 

I'm trying to do something like this: 

`sketch.document.set('foreignSymbols', arrayOfNewNodeSymbols);`

the assignment works OK, but when I check the actual array I assigned to `sketch.foreignSymbols`, I'm seeing this:

![screen shot 2019-02-19 at 3 01 55 pm](https://user-images.githubusercontent.com/4923719/53053831-5e46ad00-3457-11e9-941c-2cd377e36120.png)

I'm guessing I'm doing something wrong or am doing something that is not allowed. I'm looking to strip out some symbols based on certain conditions and rewrite the file with that new set of symbols. 

**edit** I think I figured this out; `sketch.foreignSymbols` has different object types (`symbolMaster`) than `sketch.document.foreignSymbols`.

Perhaps in the future be able to set `sketch.whatever` attrs as well as getting them?

**Comment by pcanella** [comment]
See edit above ^

**Comment by oscarotero** [comment]
Sorry for the late and thanks for the feedback. Yes, it's good idea. I will do.

**Comment by pcanella** [comment]
No worries! This tool is much appreciated 🎉
