### ISSUE TITLE
[Help] Specifics on where Detach can be used?

### ISSUE THREAD

**Issue by pcanella** [oscarotero/node-sketch#15]
I'm looking for the equivalent of `Detach from Symbol...`, am I able to do this with `detach()` somehow?  
![giphy 13](https://user-images.githubusercontent.com/4923719/53136267-3dec2080-3533-11e9-90e2-0a5b96934aaa.gif)

**Comment by oscarotero** [comment]
I didn't try but I guess It can be something like the following:

```js
const master = instance.symbolMaster; //get the master of the instance
const content = master.layers; //get the content

//...and replace the instance with the layers :)
```

**Comment by pcanella** [comment]
Got it working! Thanks!
