### ISSUE TITLE
how to save bitmapLayer to image ?

### ISSUE THREAD

**Issue by libaozhu87** [oscarotero/node-sketch#2]

**Comment by oscarotero** [comment]
In the `develop` branch I've implemented a way to export the images.
There's a plugin here: https://github.com/oscarotero/node-sketch/blob/develop/plugins/ExportImages.js and usage example here: https://github.com/oscarotero/node-sketch/blob/develop/examples/index.js#L17

I'll release a new version soon.

**Comment by oscarotero** [comment]
Ok, the new version allows to export the bitmap layers.
