### ISSUE TITLE
Preview is not updated after saving

### ISSUE THREAD

**Issue by wholcman** [oscarotero/node-sketch#28]
I'm trying to update text layers of sketch files dynamically like below.

```
const sketch = await ns.read(mySketchFile);
const page = sketch.pages[0].layers[0];
let my_layer = _.find(page.layers, { name: 'my_layer' });
my_layer.attributedString.string = myDataLayer;
sketch.save(myNewSketchFilePath)
```

The preview of the new sketch file exported is never updated as if updates have not been taken.
I have to manually open the sketch file, save it and now the preview will be OK.
You can see the issue in the demo `replace-styles` in the repo

Any ideas ?

**Comment by oscarotero** [comment]
The preview images are generated automatically by sketch (the app) when save the file. This library cannot update these images because it require to render the document to generate them. The only thing that can do is exporting the images with `sketch.exportPreviews('path/to/export/')`.

**Comment by wholcman** [comment]
If I export run `sketch.exportPreviews('path/to/export/')` after having updated a `attributedString`, the preview is not good.
Do you know this issue ?!

**Comment by oscarotero** [comment]
Yes, this library does not re-generate the previews after any change, only can export the previews existing currently in the file.
