### ISSUE TITLE
Updating Styles in Layers

### ISSUE THREAD

**Issue by sho13** [oscarotero/node-sketch#3]
Hi! Love this library, I have a problem where I'm making a change to the styles (adding color), and saving it, but the changes aren't being saved, or it'll corrupt the file :/ 

```
    ns.read(filePath)
      .then((sketch) => {     
         layers[i].getAll("style", style => {
            style.fills = [];
            style.fills[0] = {
              _class: 'color',
              alpha: endColor[3] === undefined ? undefined : endColor[3],
              blue: endColor[2],
              green: endColor[1],
              red: endColor[0],
            }
         return sketch.save(path.join(__dirname + `/output.sketch`))
          .then((success) => {
            console.log('SUCCESS')
          });
      })
```

It'll log the `success`, and the output.sketch file is there, but it'll give me this prompt when i attempt to open it

<img width="501" alt="screen shot 2017-11-21 at 3 48 35 pm" src="https://user-images.githubusercontent.com/15018312/33116488-f34f49c4-cf32-11e7-9003-6a1af8924a0a.png">

When I fix it it'll show me the original file, before any changes were made.

If i select don't fix i get::

<img width="423" alt="screen shot 2017-11-21 at 3 48 39 pm" src="https://user-images.githubusercontent.com/15018312/33116508-087db416-cf33-11e7-827a-9160a11335ef.png">

Any tips?

Thank you

**Comment by oscarotero** [comment]
Hello. I think there's some missing code in your example. (where is `layers[i]` defined?)
The method `getAll` returns an array with the result, so you have to use a `forEach` to iterate with it:

```js
layers[i].getAll('style').forEach(style => {
});
```

And I recommend to use `push` or `set` to insert new elements to a node:

```js
style.fills = [];
style.push('fills', {
  _class: 'color',
  //...
});
```

And finally, the `save` method changed in the latest version and does not returns a promise any more, but the sketch instance itself.

**Comment by sho13** [comment]
Apologies for the missing code, am working under NDA. Thank you i'll give that a shot

**Comment by sho13** [comment]
So I tried to use `push` or `set` and they both returned a TypeError: style.push/set is not a function

**Comment by oscarotero** [comment]
This is because you're not using the latest version (0.8.0).

**Comment by sho13** [comment]
So the new updated `save` function gives me this error after I logged `this.queue` and I get `null` is there something I'm doing wrong? 

```
err: RangeError: Maximum call stack size exceeded
    at Sketch.save (/node-sketch/src/Sketch.js:88:9)
    at Sketch.save (/node-sketch/src/Sketch.js:90:31)
    at Sketch.save (/node-sketch/src/Sketch.js:90:31)
    at Sketch.save (/node-sketch/src/Sketch.js:90:31)
    at Sketch.save (/node-sketch/src/Sketch.js:90:31)
    at Sketch.save (/node-sketch/src/Sketch.js:90:31)
    at Sketch.save (/node-sketch/src/Sketch.js:90:31)
    at Sketch.save (/node-sketch/src/Sketch.js:90:31)
    at Sketch.save (/node-sketch/src/Sketch.js:90:31)
    at Sketch.save (/node-sketch/src/Sketch.js:90:31)`
```
When I revert back to the original save referenced here https://github.com/oscarotero/node-sketch/commit/b99cdb470841408aa81792ba53e0bccea6fcadea#diff-1c9563195fd681cf4b3a8d5e979d6c82

I break my file back to the initial problems

**Comment by oscarotero** [comment]
Ok, that's a bug. I just released the v0.8.1 that fix this.

**Comment by sho13** [comment]
Thank you, that fixed the bug, I am curious though I've tried using `set` and `push` and it still corrupts the file and Sketch still gives me the errors as in my initial issue.

**Comment by oscarotero** [comment]
The error is because you are inserting data that does no follow the scheme of the sketch format.

A `style` node can be something like this:

```
{"_class":"style","borders":[{"_class":"border","isEnabled":false,"color":{"_class":"color","alpha":1,"blue":0.592,"green":0.592,"red":0.592},"fillType":0,"position":1,"thickness":1}],"endDecorationType":0,"fills":[{"_class":"fill","isEnabled":true,"color":{"_class":"color","alpha":1,"blue":0.6858524659863946,"green":0.4452263878267147,"red":0.07594874312621591},"fillType":0,"noiseIndex":0,"noiseIntensity":0,"patternFillType":1,"patternTileScale":1}],"miterLimit":10,"shadows":[{"_class":"shadow","isEnabled":true,"blurRadius":4,"color":{"_class":"color","alpha":1,"blue":0,"green":0,"red":0},"contextSettings":{"_class":"graphicsContextSettings","blendMode":0,"opacity":1},"offsetX":0,"offsetY":2,"spread":0}],"sharedObjectID":"7835A451-D28F-4816-9E42-372B111D0E06","startDecorationType":0}
```

You can use [this tool](http://jsonviewer.stack.hu/) to see the json structure as a tree.

A workaround could be something like this:

```js
layers[i].getAll('style').forEach(style => {
    //Get the fills of this style
    style.getAll('fill').forEach(fill => {
        fill.set('color', {
              _class: 'color',
              alpha: endColor[3] === undefined ? undefined : endColor[3],
              blue: endColor[2],
              green: endColor[1],
              red: endColor[0],
          });
    });
});
```

I didn't try this, but you get the idea.

Note: to see the data scheme of any node, you can do this:

```js
const fill = layer.get('fill').toJson();
console.log(JSON.stringify(fill));
```

**Comment by sho13** [comment]
Right I understand, however I'm trying to create the key `fill` in some cases and it seems to fail.

Is there a way to create a node?

**Comment by oscarotero** [comment]
Internally set/push uses https://github.com/oscarotero/node-sketch/blob/master/index.js#L107 to create new nodes.
What errors are you getting?

**Comment by sho13** [comment]
I see:
```
layers[i].get("style", style => {
        console.log('style:: ', style);
        style.getAll('fill').forEach(fill => {
          fill.push('color', {
            _class: 'color',
            alpha: endColor[3] === undefined ? undefined : endColor[3],
            blue: endColor[2],
            green: endColor[1],
            red: endColor[0],
          })
          console.log('fill:: ', fill);

        })
})
```
This doesn't really work, because the `fill` key isn't logged at all.

**Comment by oscarotero** [comment]
This is not correct:
```js
layers[i].get("style", style => {
});
```

`get()` is the same than `getAll()` but returns only the first element found, instead an array with all. You're passing the callback as argument, so this callback is used as a filter function. Please, see the docs https://github.com/oscarotero/node-sketch#node

you have to do this:

```js
const style = layers[i].get('style');
```

or, to iterate with all instances of style:

```js
layers[i].getAll('style').forEach(style => {
    //here the code
});
```

**Comment by sho13** [comment]
Made an attempt with this version, my changes didn't persist:: 

```
      let style = layers[i].get("style");

      style.getAll("fill").forEach(fill => {
        console.log('fill:: ', fill);

        fill.set('color', {
          _class: 'color',
          alpha: endColor[3] === undefined ? undefined : endColor[3],
          blue: endColor[2],
          green: endColor[1],
          red: endColor[0],
        })
      })
```

this also doesn't persist with::

```      
layers[i].getAll("style").forEach(style => {
        style.getAll('fill').forEach(fill => {
          fill.push('color', {
            _class: 'color',
            alpha: endColor[3] === undefined ? undefined : endColor[3],
            blue: endColor[2],
            green: endColor[1],
            red: endColor[0],
          })
        })
      })
```

you're telling me that `fill` would be created upon `push`/`set`, is there any way to confirm that the node is created?

**Comment by oscarotero** [comment]
`push` adds a new value in the array and `set` replaces the old value with a new value. In your case, each fill has only a color (a layer can have several fills, but each fill contains only a color, as you can see in the data structure). So you must use `set`, not `push`, because `fill.color` is not an array.

I just tried this and works fine for me:

```js
file.pages[0].getAll('style').forEach(style => {
    style.getAll('fill').forEach(fill => {
            fill.set('color', {
                _class: 'color',
                alpha: 0.5,
                blue: 0.5,
                green: 0.4,
                red: 0.3
            });
    })
});
```

**Comment by sho13** [comment]
Okay, thank you for the clarification, but what happens in the case that `fill` doesn't exist? 

It doesn't seem to hit the `set` because the `fill` doesn't exist in that `style` object.

```javascript
layers[i].getAll("style").forEach(style => {
        console.log('style.fill:: ', style.fill);
        style.getAll('fill').forEach(fill => {
          console.log('HIT')
          fill.set('color', {
            _class: 'color',
            alpha: endColor[3] === undefined ? undefined : endColor[3],
            blue: endColor[2],
            green: endColor[1],
            red: endColor[0],
          })
        })
      })
```

**Comment by sho13** [comment]
Aight bro, I figured it out. 

here's the snippet:: 

```javascript
layers[i].getAll("style").forEach(style => {
        console.log('style.fill:: ', style.fill);
        style.fill = []
        style.push('fill', {
          _class: 'color',
          alpha: endColor[3] === undefined ? undefined : endColor[3]/255,
          blue: endColor[2]/255,
          green: endColor[1]/255,
          red: endColor[0]/255,
        })
        console.log('style.fill:: ', style.fill);
      })
```

i had to set a fill property with an array and then push the object onto it.

the problem is now though, it still doesn't persist into the saved sketch file.

**Comment by oscarotero** [comment]
Another solution is simply set an array of fills:

```js
style.set('fill', [
    {
        _class: 'color',
        //etc...
    }
]);
```

> the problem is now though, it still doesn't persist into the saved sketch file.

I just execute this code and works fine. I have a result.sketch file with the colors changed.

```js
sketch
    .read(__dirname + '/example.sketch')
    .then(file => {
        file.pages[0].getAll('style').forEach(style => {
            style.getAll('fill').forEach(fill => {
                    fill.set('color', {
                        _class: 'color',
                        alpha: 0.5,
                        blue: 0.5,
                        green: 0.4,
                        red: 0.3
                    });
            })
        });

        file.save(__dirname + '/result.sketch');
    })
    .catch(err => {
        console.error('Error reading the sketch file');
        console.error(err);
    });
```

**Comment by sho13** [comment]
I see would you say that if I have a recursive function running inside the `.then()` that there'd be a scoping issue?

**Comment by oscarotero** [comment]
I run a recursive function (to replace all colors) and then save the file. Everything is in the same place and it works fine. I don't understand what do you mean with scoping issue. Can I see your whole code?

**Comment by sho13** [comment]
Sure, 

```javascript
  updateSketch: (req, res) => {
    let { pageID, objectID, type, endColor } = req.body;
    endColor = endColor.map(n => n / 255);

    ns.read(filePath)
      .then((sketch) => {
        let { pages } = sketch;
        for(let i = 0; i < pages.length; i++) {
          if(pages[i].do_objectID === pageID) {
            // console.log('pages:: ', pages[i]);
            let { layers } = pages[i];
            recurseSketch(layers, objectID, endColor, type);
          }
        }
        console.log('save???')
        sketch.save(path.join(__dirname + `/../../uploadedSketchFiles/output.sketch`))
      }).catch((e) => { console.log('err:', e)})
  },
```

this is the recursive function 

```javascript
const recurseSketch = (layers, objectID, endColor, type) => {
  for(let i = 0; i < layers.length; i++) {
    if(layers[i].do_objectID === objectID) {
      layers[i].getAll("style").forEach(style => {
        switch (type) {
          case 'backgroundColor':
            console.log('style.fill:: ', style.fill);
            style.fill = []
            return style.push('fill', {
              _class: 'color',
              alpha: endColor[3] === undefined ? undefined : endColor[3],
              blue: endColor[2],
              green: endColor[1],
              red: endColor[0],
            })
            break;
          default:
            console.log('SUp')
            return;
        }
        console.log('style.fill:: ', style.fill);
      })
    }
    if(layers[i] !== undefined && layers[i].layers !== undefined) {
      recurseSketch(layers[i].layers, objectID, endColor, type);
    }
  }
}
```

**Comment by oscarotero** [comment]
This should save the changes in `output.sketch`. Are you sure that any change is performed?

Another thing I see: `get()` and `getAll()` search the node recursively and accept functions as filter, so you don't need all that code. Just:

```js
page.getAll(layer => layer.do_objectID === objectID).forEach(layer => {
    layer.getAll('style').forEach(style => {
    });
})
```

**Comment by sho13** [comment]
Thanks for the clarification, yeah for some reason it still doesn't save the changes in the `output.sketch`
i made the change to:: 
```javascript
          pages[i].getAll(layer => {
            layer.do_objectID === objectID
          }).forEach(layer => {
            layer.getAll('style').forEach(style => {
              style.set('fill', [{
                _class: 'color',
                alpha: endColor[3] === undefined ? undefined : endColor[3],
                blue: endColor[2],
                green: endColor[1],
                red: endColor[0],
              }])
            })
          })
```
and the changes still aren't persisting into the `output.sketch` files
