### ISSUE TITLE
Syncing shared styles

### ISSUE THREAD

**Issue by arronhunt** [oscarotero/node-sketch#4]
I'm writing a small script to update a shared style and apply it to all layers that inherit it. Currently I can update the shared style, but I'm not quite sure how to "sync" it to all layers. 

I see there's an UpdateStyles plugin, but that takes styles from an external document and applies them to another. I want to update shared styles within a document and then update all layers that use it.

**Comment by oscarotero** [comment]
If I understand correctly, you have updated the shared styles and want to apply these changes to all layers using this style, right?

You can do something like this: https://github.com/oscarotero/node-sketch/blob/master/plugins/UpdateStyles.js#L29 removing the code related with the new shared styles replacement. For example:

```js
//Iterate with the sharedStyles
sketch.sharedStyles.forEach(sharedStyle => {

    //Update the referencies
    sketch.pages.forEach(page => {
        page
            .getAll(
                'style',
                style =>
                    style.sharedObjectID === sharedStyle.do_objectID
            )
            .forEach(style => style.applySharedStyle(newSharedStyle));
    });
});
```
